#pragma once

#define ARCH_PAGE_SIZE_SMALL 0xfa00
#define ARCH_PAGE_SIZE_LARGE 512 * ARCH_PAGE_SIZE_SMALL
#define ARCH_PAGE_SIZE_HUGE 512 * ARCH_PAGE_SIZE_LARGE

#define ARCH_PAGE_SIZE_DEFAULT ARCH_PAGE_SIZE_SMALL
